### ISSUE TITLE
Unpickle doesn't work with skeltonkey

### ISSUE THREAD

**Issue by Majd223** [sizemore0125/skeletonkey#46]
to reproduce, unlock skeletonkey into args then numpy.savez the object then try to unpickle the npz will give a maximum recursion depth exceeded error.
```
>>> d = np.load('./vdp_ssm-dpc-epochs.npz', allow_pickle=True)
>>> d
<numpy.lib.npyio.NpzFile object at 0x7ffba6b0e280>
>>> v = d['arr_0'].item().get('vdp_ssm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/research-groups/hutchinson/workspace/safim/epicenv/lib64/python3.9/site-packages/numpy/lib/npyio.py", line 253, in __getitem__
    return format.read_array(bytes,
  File "/cluster/research-groups/hutchinson/workspace/safim/epicenv/lib64/python3.9/site-packages/numpy/lib/format.py", line 781, in read_array
    array = pickle.load(fp, **pickle_kwargs)
  File "/cluster/research-groups/hutchinson/workspace/safim/epicenv/lib64/python3.9/site-packages/skeletonkey/config.py", line 96, in __getattr__
    if self.__unparsed_args is not None and name in self.__unparsed_args:
  File "/cluster/research-groups/hutchinson/workspace/safim/epicenv/lib64/python3.9/site-packages/skeletonkey/config.py", line 96, in __getattr__
    if self.__unparsed_args is not None and name in self.__unparsed_args:
  File "/cluster/research-groups/hutchinson/workspace/safim/epicenv/lib64/python3.9/site-packages/skeletonkey/config.py", line 96, in __getattr__
    if self.__unparsed_args is not None and name in self.__unparsed_args:
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by sizemore0125** [comment]
Are you trying to pickle an object instantiated with skelletonkey, or are you trying to pickle the args object itself?

**Comment by Majd223** [comment]
I am trying to pickle the args object itself.
